version: '3.1'

services:
  frontend2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend2
    ports:
      - 80:3000
    volumes:
      - .:/var/www/html
    networks:
      - frontend
      - backend_backendnetwork
    environment:
      - CONTAINER_TIMEZONE=Asia/Bangkok
      - VIRTUAL_HOST=local-vhost.dev

networks:
  frontend2:
    driver: bridge
  backend_backendnetwork:
    external: true