name: CD

on:
  workflow_run:
    workflows: ["Building"]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd server
            docker-compose pull service_name
            docker-compose stop service_name
            docker-compose up -d  ervice_name
            docker image prune -f