name: CI

on:
  push:
    branches: infra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_ACC }}
          password: ${{ secrets.GH_PAT }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/github_user/image_name:latest

      - name: Push Docker image to Github Container registry
        run: docker push ghcr.io/github_user/image_name:latest